# Site settings
title: Great New Blog Title
author:
  name: Ian Hellman
  email: ian.hellman@gmail.com
description: "Great site about Jekyll on GH-Pages."

# Build settings
remote_theme: jekyll/minima
